### ISSUE TITLE
`__getitem__` fails to raise IndexError

### ISSUE THREAD

**Issue by gilbertmike** [Fibertree-Project/fibertree#11]
With the following code:
```
z = Tensor(rank_ids=["M", "N"])
z.setName("Z")
z.setMutable(True)

z_m = z.getRoot()
#
# Hack to fill in all the entries in z
# This allows us to pretend the tensor is dense
#
n_fiber = Fiber(coords=range(N), initial=1)
m_fiber = Fiber(coords=range(M), initial=1)

for m, (z_n, _) in z_m << m_fiber:
    for n, (z_ref, _) in z_n << n_fiber:
        z_ref <<= 0
        
z.getRoot()[0][0]
```

There were two problems:

- The first indexing operation `z.getRoot()[0]` wants to raise an `IndexError`. I think this shouldn't happen.
- The code fails to raise the `IndexError`.

Traceback follows.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 17
     14     for n, (z_ref, _) in z_n << n_fiber:
     15         z_ref <<= 0
---> 17 z.getRoot()[0][0]

File /usr/local/lib/python3.8/dist-packages/fibertree/core/fiber.py:1874, in Fiber.__getitem__(self, keys)
   1871     key += len(self)
   1873 if key < 0 or key >= len(self):
-> 1874     raise(IndexError, f"The index ({key}) is out of range")
   1876 new_payload = self.payloads[key]
   1878 if len(key_cdr):
   1879     # Recurse down the fiber tree

TypeError: exceptions must derive from BaseException

```

**Comment by nandeeka** [comment]
Thanks for raising this issue. Here are my comments:
1. An `IndexError` should be raised with `z.getRoot()[0]`. HiFiber does not insert empty payloads with `<<` for performance reasons. Therefore, your loop nest actually has no impact on `z`. Therefore, there is nothing at the position 0 for you to access, and it raises an `IndexError`.
2. We are seeing the `TypeError` because the `IndexError` was being raised incorrectly. Thank you for pointing it out. The fix for this should be up shortly.
